name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: 'stage-446710' # Update to your Google Cloud project ID
  REGION: 'me-west1' # Update to your region
  REPO_NAME: 'backend-image' # Update to your repository name
  SERVICE_NAME: 'backend-service' # Update to your Cloud Run service name

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_backend_key }}

      - name: Authenticate Docker to Artifact Registry
        run: gcloud auth configure-docker 

      - name: Build Docker image
        run: docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:$GITHUB_SHA .

      - name: Push Docker image
        run: docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:$GITHUB_SHA \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --port 8080



